### ISSUE TITLE
False positive: "undeclared annotation" loc on parse tree

### ISSUE THREAD

**Issue by rodinaarssen** [usethesource/rascal-core#5]
![image](https://user-images.githubusercontent.com/19751241/63007270-9e27a380-be80-11e9-8955-af1f246b3fdb.png)

**Comment by DavyLandman** [comment]
👍 great all these reports!

does it also happen if you import `ParseTree`?

**Comment by rodinaarssen** [comment]
Good intuition, with `ParseTree` imported, this isn't triggered

**Comment by DavyLandman** [comment]
Tnx, I forgot if ParseTree should be considered automatically imported if you have syntax rules in your model. I think @jurgenvinju knows.

**Comment by PaulKlint** [comment]
In the future it would be nice to include  in the error message a list of modules where the undefined name *is* declared. For now I close this issue.
