### ISSUE TITLE
False positive: "extended module unused" if layout definition present in extendee

### ISSUE THREAD

**Issue by rodinaarssen** [usethesource/rascal-core#6]
```rascal
module A

layout L = [(]*;
```
![image](https://user-images.githubusercontent.com/19751241/63007062-3f622a00-be80-11e9-9084-5da88df876d2.png)
```
rascal>(S)`s(s`
S: (S) `s(s
```

**Comment by DavyLandman** [comment]
Nice one, I remember @PaulKlint mentioning that he was sure that the unused detection wasn't bullet proof, so I think he would like this nice example.

**Comment by jurgenvinju** [comment]
It seems likely that the implicit use of `A::L` in B is missed, or does this also break when we use something other than a `layout` production?

**Comment by PaulKlint** [comment]
Slowly all hidden dependencies on import/extend are becoming clear. This specific issue has been solved. Thanks for reporting!
