### ISSUE TITLE
Missing dead code detection after `insert`

### ISSUE THREAD

**Issue by rodinaarssen** [usethesource/rascal-core#8]
The first `println` statement should be marked as dead code.
![image](https://user-images.githubusercontent.com/19751241/66555923-b26de100-eb4f-11e9-82d2-3a25a7302801.png)

**Comment by PaulKlint** [comment]
Great find!

**Comment by rodinaarssen** [comment]
The same goes for `fail;`.

**Comment by PaulKlint** [comment]
The problems were twofold:

- `insert` was not handled
- the argument of `return` was not analyzed.

My impression is that `fail` works now as well. If you have examples where this analysis fails then I will be happy to fix them.
